# Generated by Django 3.1 on 2021-05-07 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20210507_0235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PokemonBase',
            new_name='userBase',
        ),
        migrations.RemoveField(
            model_name='pokemonuser',
            name='pokemon_name',
        ),
        migrations.AddField(
            model_name='pokemonuser',
            name='pokemon_id',
            field=models.IntegerField(null=True),
        ),
    ]
